commit_message: "i18n(%language%): crowdin update"
append_commit_message: false

pull_request_title: "i18n: update translations [crowdin bot]"

files:
  - source: /frontend/i18n/ja.yml
    translation: /frontend/i18n/%two_letters_code%.yml
  - source: /backend/config/locales/ja.yml
    translation: /backend/config/locales/%two_letters_code%.yml
