name: "[sub-audio] Lint, test"

on:
  push:
    paths:
      - "sub-audio/**"
      - ".github/workflows/sub-audio-*.yml"
      - "Rakefile"
      - "config.test.yml"
    branches:
      - main
  pull_request:
    paths:
      - "sub-audio/**"
      - ".github/workflows/sub-audio-*.yml"
      - "Rakefile"
      - "config.test.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
      - name: Setup .env
        run: |
          cp ./config.test.yml ./config.yml
          rake configure

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version-file: sub-audio/.python-version

      - name: Install rye
        run: |
          pip install rye

      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-rye-${{ hashFiles('./sub-audio/*.lock') }}
          restore-keys: |
            ${{ runner.os }}-rye-

      - name: Install dependencies
        working-directory: ./sub-audio
        run: rye sync

      - name: Run sub-audio lint
        working-directory: ./sub-audio
        run: |
          rye run lint

      - name: Run sub-audio test
        working-directory: ./sub-audio
        run: |
          rye run test

      - name: Build image
        uses: ./.github/actions/build
        with:
          directory-name: sub-audio
